theme: jekyll-theme-hacker
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
 - jekyll-seo-tag
 - jekyll-avatar
 - jekyll-include-cache
url: "https://geekbuilt.github.io/cissp"
baseurl: ""
title: CISSP Prep
description: "CISSP Study Guide and notes"
author:
  github: https://github.com/twofivesixbit
