theme: jekyll-theme-hacker
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
 - jekyll-seo-tag
 - jekyll-avatar
 - jekyll-include-cache
url: "https://sgn.256-bit.com"
baseurl: ""
title: CISSP Prep
description: "CISSP Study Guide and notes"
